"""Counterbalancing for the live follow-up study — the ONE place block order is
decided. ``docs/live_study_setup.md`` section 2; CLAUDE.md's "Counterbalancing"
paragraph is the corrected record this file implements.

THE DESIGN
==========
One within-subject factor, K (personalization data), at three levels — the
three checkpoints ``build_study_checkpoints.py`` mints per participant:

    condition 0 = K=0   the driver's own LODO population model (no adaptation)
    condition 1 = K=4   adapted on their first 4 phone-call labels
    condition 2 = K=8   adapted on their first 8

Each participant drives all three, one per block, so K is BLOCKED rather than
interleaved — a driver's block-3 rating cannot be split by K, only their
call-by-call responses within it can. What varies across participants is the
ORDER the three blocks are presented in, and that order is what this file
counterbalances.

ALL 3! = 6 ORDERS, NOT A LATIN SQUARE
======================================
A 3x3 Latin square uses only 3 of the 6 permutations of (0,1,2) — it balances
each condition's mean SERIAL POSITION (first/second/third) but not which pairs
of conditions land adjacent to which. Complete counterbalancing is strictly
stronger and 12 divides evenly into 6, so there is no reason to accept the
weaker guarantee.

This matters more here than in a typical within-subject design because
**K=0 is one of the levels**. A driver who meets the unpersonalized condition
AFTER a well-personalized block plausibly rates it harsher by contrast than one
who meets it first — first-order carryover is a live confound, not a formality,
and only balancing all 6 orders (so K=0 appears first, second and third equally
often, paired against each other condition equally often in each direction)
neutralizes it in aggregate.

12 PARTICIPANTS = 2 FULL REPLICATES, NO REMAINDER
==================================================
6 orders x 2 = 12, so every order is used exactly twice and nothing is
partially balanced. This is what makes 12 the right cohort size for THIS
design — not an approximation to a larger ideal.

ASSIGNMENT: FIXED AND EXPLICIT, NOT RANDOM AT RUNTIME
======================================================
Same reasoning as ``TRAFFIC_SEED_PLAN`` and ``folds.py``: a table generated
fresh per invocation could not be guaranteed to match between the person who
consented a participant to sequence 4 and the process that actually serves it a
week later. It is generated ONCE (see the shuffle below), then written down —
so "which order did participant 007 get" has exactly one answer, checkable by
reading this file, forever.

Two properties are enforced by ``_check()`` at import, not merely aimed for:

  1. Each of the 6 orders is used exactly twice across the 12 participants
     (complete counterbalancing, no remainder).
  2. Within each ``TRAFFIC_SEED_PLAN`` block of 4 participants (001-004,
     005-008, 009-012), all 4 assigned orders are DISTINCT.

(2) is the operative meaning of "independent of the traffic-scenario pair"
(CLAUDE.md, §2): the traffic assignment is already blocked in groups of 4, so if
this table also clustered same-order participants inside one traffic block, a
traffic effect and an order effect could be mistaken for each other. Requiring
the 4 within a block to take 4 different orders is a stronger, mechanically
checkable version of "assigned independently" — weaker properties (e.g. merely
"not identical to the traffic pairing") would pass by accident and prove
nothing.

The table below is the result of shuffling two copies of the 6 permutations
with ``random.Random(2033)`` and taking the first seed (searched from 2026,
the design's decision year) whose draw satisfies both properties BY LUCK, not
by construction — i.e. the seed is not hand-picked further than "the first one
that works", so there is no room to have tuned it toward some outcome. See
``_regenerate()`` to reproduce or replace it.
"""
from __future__ import annotations

import itertools
import random
from typing import Dict, Sequence, Tuple

from ProVoice.training_scripts.folds import ALL_PIDS, SCENARIO_BLOCKS  # noqa: E402

# The 6 possible orders, as condition-index permutations. Index into this with
# an order to get e.g. (2, 0, 1) = "block 1 serves condition 2 (K=8), block 2
# serves condition 0 (K=0), block 3 serves condition 1 (K=4)".
ORDERS: Tuple[Tuple[int, int, int], ...] = tuple(itertools.permutations((0, 1, 2)))
assert len(ORDERS) == 6

# Search seed and the first one whose draw satisfies both _check() properties.
# Recorded so the table is REPRODUCIBLE, not just fixed -- see _regenerate().
_SEED_SEARCH_START = 2026
_CHOSEN_SEED = 2033

# participant -> (condition for block 1, condition for block 2, condition for block 3)
#
# Generated by _regenerate(_CHOSEN_SEED); pasted here as a literal so the
# mapping survives independently of this module's generation code, the same
# way TRAFFIC_SEED_PLAN and VALIDATION_FOLDS are literals rather than computed
# at import. Do not hand-edit a single entry -- regenerate the whole table (or
# pin a different participant's order via PINNED_OVERRIDES below) so property
# (1) and (2) stay provable rather than merely true today.
BLOCK_ORDER: Dict[str, Tuple[int, int, int]] = {
    "001": (2, 0, 1),
    "002": (1, 2, 0),
    "003": (0, 1, 2),
    "004": (1, 0, 2),
    "005": (2, 0, 1),
    "006": (2, 1, 0),
    "007": (0, 2, 1),
    "008": (1, 2, 0),
    "009": (2, 1, 0),
    "010": (0, 2, 1),
    "011": (1, 0, 2),
    "012": (0, 1, 2),
}

# A participant who drops out mid-sequence and is re-consented under a NEW id
# can be pinned to their predecessor's remaining order here, rather than
# forcing a full regeneration (which would reshuffle everyone). Empty by
# design -- see docs/live_study_setup.md section 2 before adding an entry: an
# override changes the replicate count for whichever order it duplicates.
PINNED_OVERRIDES: Dict[str, Tuple[int, int, int]] = {}


def _regenerate(seed: int) -> Dict[str, Tuple[int, int, int]]:
    """Reproduce (or replace) BLOCK_ORDER. Does not mutate module state.

    Two full copies of the 6 orders, shuffled with ``random.Random(seed)`` and
    assigned to ALL_PIDS in order. Exists so the table above is a RESULT, not
    an assertion -- run this to verify it, or to search a new seed if
    PINNED_OVERRIDES ever forces a regeneration.
    """
    pool = list(ORDERS) * (len(ALL_PIDS) // len(ORDERS))
    random.Random(seed).shuffle(pool)
    return dict(zip(ALL_PIDS, pool))


def block_order(participantid: str) -> Tuple[int, int, int]:
    """This participant's (block1, block2, block3) -> condition mapping.

    Raises rather than guessing: an unplanned participant is the same failure
    mode ``TRAFFIC_SEED_PLAN`` already treats as fatal, and for the same
    reason -- silently improvising an order here would run a real session
    outside the counterbalancing the design's power analysis assumes.
    """
    order = PINNED_OVERRIDES.get(participantid) or BLOCK_ORDER.get(participantid)
    if order is None:
        raise KeyError(
            f"No block order planned for participant {participantid!r}. Add "
            f"them to BLOCK_ORDER (regenerating properly -- see _regenerate) "
            f"or PINNED_OVERRIDES (only for a drop-out's replacement id) "
            f"before running their session.")
    return order


def condition_for_block(participantid: str, block_idx: int) -> int:
    """The --condition to serve for this participant's block_idx (1, 2 or 3)."""
    if block_idx not in (1, 2, 3):
        raise ValueError(f"block_idx must be 1, 2 or 3; got {block_idx!r}")
    return block_order(participantid)[block_idx - 1]


def _check() -> None:
    ids = set(BLOCK_ORDER) | set(PINNED_OVERRIDES)
    if ids != set(ALL_PIDS):
        raise AssertionError(
            f"study_blocks must cover exactly {ALL_PIDS}, got {sorted(ids)}")

    effective = {p: (PINNED_OVERRIDES.get(p) or BLOCK_ORDER[p]) for p in ALL_PIDS}
    for p, order in effective.items():
        if sorted(order) != [0, 1, 2]:
            raise AssertionError(
                f"{p}: {order!r} is not a permutation of the 3 conditions")

    # Property 1 -- complete counterbalancing: each of the 6 orders used
    # exactly (len(ALL_PIDS) // 6) times, no remainder.
    reps = len(ALL_PIDS) // len(ORDERS)
    if len(ALL_PIDS) % len(ORDERS):
        raise AssertionError(
            f"{len(ALL_PIDS)} participants does not divide evenly into "
            f"{len(ORDERS)} orders -- counterbalancing would be partial")
    counts: Dict[Tuple[int, int, int], int] = {o: 0 for o in ORDERS}
    for order in effective.values():
        counts[order] += 1
    bad = {o: n for o, n in counts.items() if n != reps}
    if bad:
        raise AssertionError(
            f"orders not used exactly {reps} times each: {bad} "
            f"(full counts: {counts})")

    # Property 2 -- independence from the traffic-scenario blocking: within
    # each SCENARIO_BLOCKS group, all assigned orders must be distinct.
    for blk in SCENARIO_BLOCKS:
        seqs = [effective[p] for p in blk]
        if len(set(seqs)) != len(blk):
            raise AssertionError(
                f"traffic block {blk} does not get {len(blk)} distinct block "
                f"orders ({seqs}) -- order would be confounded with traffic "
                f"scenario for this group")


_check()


if __name__ == "__main__":
    # Print the table as a sanity check / for pasting into a consent-tracking
    # sheet -- never read by any other module.
    print("participant | block1 | block2 | block3   (condition indices)")
    for p in ALL_PIDS:
        b1, b2, b3 = block_order(p)
        print(f"    {p}     |   {b1}    |   {b2}    |   {b3}")
